### ISSUE TITLE
demo app crashes on launch -org.greenrobot.eventbus.EventBusException: Subscriber class com.yefeng.night.btprinter.MainActivity_ and its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by androiddevg** [yefengfreedom/BtPrinter#8]
classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8' In project level Gradle 

In app level gradle 
def AAVersion = '4.6.0'
targetSdkVersion 29

annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
implementation "org.androidannotations:androidannotations-api:$AAVersion"

Even If pro-guard rules set. 

com.yefeng.night.btprinter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yefeng.night.btprinter, PID: 15563
    java.lang.RuntimeException: **Unable to start activity ComponentInfo{com.yefeng.night.btprinter/com.yefeng.night.btprinter.MainActivity_}: org.greenrobot.eventbus.EventBusException: Subscriber class com.yefeng.night.btprinter.MainActivity_ and its super classes have no public methods with the @Subscribe annotation**
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2576)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5737)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
     Caused by: org.greenrobot.eventbus.EventBusException: Subscriber class com.yefeng.night.btprinter.MainActivity_ and its super classes have no public methods with the @Subscribe annotation
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:67)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:143)
        at com.yefeng.night.btprinter.base.BaseActivity.onStart(BaseActivity.java:19)
        at com.yefeng.night.btprinter.bt.BluetoothActivity.onStart(BluetoothActivity.java:50)
        at com.yefeng.night.btprinter.MainActivity.onStart(MainActivity.java:46)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1245)
        at android.app.Activity.performStart(Activity.java:6325)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2533)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5737) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)

**Comment by yefengjie** [comment]
This demo project was written few years ago, so many third part library's api has changed. you can just read the source code.
